### ISSUE TITLE
Issue from CRAN

### ISSUE THREAD

**Issue by JLP-BioInf** [jpbida/RRNA#1]
Hello,

Are you still maintaining this package? There are very simple fixes to be made that will stop your package being archived. If you no longer maintain, please LMK. because I depend on your package and would take maintenance on.

J

**Comment by jpbida** [comment]
Thank you for the support. Merged the changes for version 1.3 submission.

**Comment by jpbida** [comment]
Merged the changes for a version 1.3 submission to CRAN

**Comment by JLP-BioInf** [comment]
Perfect, that is great news. Do anticipate much action with RRNA in the near future? It could be good to “roxygenise” it but I appreciate this is a rather annoying job,



----------------------------------------------------
Jon Price
Bioinformatician - PDRA
Miska Lab
Department of Biochemisrty
University of Cambridge
Tennis Court Rd, Cambridge, CB2 1QN
***@***.******@***.***>
https://www.ericmiskalab.org/#<https://www.ericmiskalab.org/>
Apologies for any typographical errors this
email was written without the help of AI
----------------------------------------------------



From: Jp Bida ***@***.***>
Date: Wednesday, 24 April 2024 at 21:19
To: jpbida/RRNA ***@***.***>
Cc: Jon Price ***@***.***>, Author ***@***.***>
Subject: Re: [jpbida/RRNA] Issue from CRAN (Issue #1)

Merged the changes for a version 1.3 submission to CRAN
